###1、本地配置
###在本地创建application-7009 然后
#spring:
# profiles:
#  active: 7009
spring:
  profiles:
    active: prod
  application:
    name: Server-Consumer-demo
    #从micronote-config获取本地的config配置
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: micronote-config

#开启熔断
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://wyedward:123456@eureka7001.com:7001/eureka/,http://wyedward:123456@eureka7002.com:7002/eureka/,http://wyedward:123456@eureka7003.com:7003/eureka/