spring:
  profiles:
    active: 7009
  application:
    name: Server-Consumer-demo

#开启熔断
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://wyedward:123456@eureka7001.com:7001/eureka/,http://wyedward:123456@eureka7002.com:7002/eureka/,http://wyedward:123456@eureka7003.com:7003/eureka/